package net.consensys.eventeum.dto.event.parameter;

import com.fasterxml.jackson.annotation.JacksonAnnotationsInside;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

//Can't emphasise enough how much I hate this.
//TODO Custom deserializer
@Retention(RetentionPolicy.RUNTIME)
@JacksonAnnotationsInside
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = StringParameter.class, name = "address"),

        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes1"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes2"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes3"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes4"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes5"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes6"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes7"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes8"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes9"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes10"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes11"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes12"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes13"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes14"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes15"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes16"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes17"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes18"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes19"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes20"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes21"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes22"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes23"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes24"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes25"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes26"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes27"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes28"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes29"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes30"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes31"),
        @JsonSubTypes.Type(value = StringParameter.class, name = "bytes32"),

        @JsonSubTypes.Type(value = StringParameter.class, name = "string"),

        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint8"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint16"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint24"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint32"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint40"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint48"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint56"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint64"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint72"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint80"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint88"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint96"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint104"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint112"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint120"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint128"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint136"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint144"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint152"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint160"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint168"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint176"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint184"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint192"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint200"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint208"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint216"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint224"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint232"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint240"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint248"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "uint256"),

        @JsonSubTypes.Type(value = NumberParameter.class, name = "int8"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int16"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int24"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int32"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int40"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int48"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int56"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int64"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int72"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int80"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int88"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int96"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int104"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int112"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int120"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int128"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int136"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int144"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int152"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int160"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int168"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int176"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int184"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int192"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int200"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int208"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int216"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int224"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int232"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int240"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int248"),
        @JsonSubTypes.Type(value = NumberParameter.class, name = "int256"),

        @JsonSubTypes.Type(value = ArrayParameter.class, name = "address-array"),

        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes1-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes2-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes3-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes4-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes5-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes6-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes7-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes8-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes9-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes10-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes11-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes12-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes13-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes14-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes15-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes16-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes17-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes18-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes19-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes20-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes21-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes22-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes23-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes24-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes25-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes26-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes27-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes28-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes29-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes30-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes31-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "bytes32-array"),

        @JsonSubTypes.Type(value = ArrayParameter.class, name = "string-array"),

        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint8-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint16-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint24-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint32-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint40-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint48-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint56-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint64-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint72-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint80-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint88-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint96-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint104-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint112-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint120-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint128-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint136-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint144-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint152-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint160-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint168-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint176-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint184-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint192-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint200-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint208-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint216-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint224-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint232-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint240-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint248-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "uint256-array"),

        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int8-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int16-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int24-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int32-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int40-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int48-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int56-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int64-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int72-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int80-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int88-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int96-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int104-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int112-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int120-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int128-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int136-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int144-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int152-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int160-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int168-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int176-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int184-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int192-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int200-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int208-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int216-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int224-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int232-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int240-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int248-array"),
        @JsonSubTypes.Type(value = ArrayParameter.class, name = "int256-array")
})
public @interface ParameterSubTypes {
}
